name: devScripts
on:
  workflow_dispatch:
  schedule:
    - cron: '50 6 * * 0'

jobs:
  update:
    uses: salesforcecli/github-workflows/.github/workflows/devScriptsUpdate.yml@main
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SF_CLI_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
